# Copyright IBM Corp All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0


[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/mux"

[[constraint]]
  branch = "master"
  name = "github.com/grantae/certinfo"

[[constraint]]
  branch = "master"
  name = "github.com/hyperledger/fabric"

[[constraint]]
  branch = "master"
  name = "github.com/cloudflare/cfssl"

[[constraint]]
  branch = "master"
  name = "github.com/kisielk/sqlstruct"

[[constraint]]
  branch = "master"
  name = "github.com/op/go-logging"

[[constraint]]
  name = "gopkg.in/ldap.v2"
  version = "2.5.0"

[prune]
  go-tests = true
  unused-packages = true
