#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
FROM hyperledger/fabric-tools:_FABRIC_TAG_
COPY payload/fabric-ca-client /usr/local/bin
RUN chmod +x /usr/local/bin/fabric-ca-client
RUN wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O jq
RUN chmod +x ./jq
RUN mv ./jq /usr/local/bin/jq