# keepalived1:
#     image: neoassist/docker-keepalived:latest
#     container_name: keepalived
#     environment:
#       - VIRTUAL_IP=172.17.8.150
#       - VIRTUAL_MASK=24
#       - CHECK_IP=any
#       - CHECK_PORT=80
#       - VRID=150
#       - INTERFACE=eth0
#     command: sh -c '/usr/sbin/sysctl -w net.ipv4.ip_nonlocal_bind=1'
version: '2'

services:
  haproxy0:
      image: haproxy:latest
      container_name: haproxy0
      volumes:
        - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
      environment:
        - EXPOSE=7054
      links:
        - fabric-ca-server1:fabric-ca-server1
        - fabric-ca-server2:fabric-ca-server2
      # command: sh -c '/usr/sbin/sysctl -w net.ipv4.ip_nonlocal_bind=1'

  haproxy1:
      image: haproxy:latest
      container_name: haproxy1
      volumes:
        - "./haproxy1.cfg:/usr/local/etc/haproxy/haproxy.cfg"
      environment:
        - EXPOSE=3306
      links:
        - mariadb-node-1:mariadb-node-1
        - mariadb-node-2:mariadb-node-2

  mariadb-node-1:
      image: mariadb:latest
      hostname: mariadb-node-1
      # ports:
      #   - 13306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=rootpw
        - REPLICATION_PASSWORD=test
        # - NODE_NAME=mariadb-node-1
      volumes:
        - "./my.cnf:/etc/mysql/my.cnf"
      command: --wsrep-new-cluster
              # - GALERA=On
              # - CLUSTER_NAME=ca_galera
              # - CLUSTER_ADDRESS=gcomm://mariadb-node-1,mariadb-node-2,mariadb-node-3


  mariadb-node-2:
      image: mariadb:latest
      hostname: mariadb-node-2
      ports:
        - 13307:3306
      # links:
      #   - mariadb-node-1
      environment:
        - MYSQL_ROOT_PASSWORD=rootpw
        - REPLICATION_PASSWORD=test
        # - NODE_NAME=mariadb-node-2
      volumes:
        - "./my2.cnf:/etc/mysql/my.cnf"
        # - GALERA=On
        # - CLUSTER_NAME=ca_galera
        # - CLUSTER_ADDRESS=gcomm://mariadb-node-1,mariadb-node-2,mariadb-node-3

  mariadb-node-3:
      image: mariadb:latest
      hostname: mariadb-node-3
      ports:
        - 13308:3306
      # links:
      #   - mariadb-node-1
      environment:
        - MYSQL_ROOT_PASSWORD=rootpw
        - REPLICATION_PASSWORD=test
        # - NODE_NAME=mariadb-node-3
      volumes:
        - "./my3.cnf:/etc/mysql/my.cnf"
        # - GALERA=On
        # - CLUSTER_NAME=ca_galera
        # - CLUSTER_ADDRESS=gcomm://mariadb-node-1,mariadb-node-2,mariadb-node-3

  fabric-ca-server1:
     image: hyperledger/fabric-ca
     container_name: fabric-ca-server1
     ports:
       - 7051:7054
     environment:
       - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
     volumes:
       - "./fabric-ca-server:/etc/hyperledger/fabric-ca-server"
       - "./wait-for-it.sh:/etc/hyperledger/wait-for-it.sh"
     command: sh -c '/etc/hyperledger/wait-for-it.sh mariadb-node-1:3306 -- fabric-ca-server start -b admin:adminpw'
     links:
       - mariadb-node-1
       - haproxy1

  fabric-ca-server2:
     image: hyperledger/fabric-ca
     container_name: fabric-ca-server2
     ports:
       - 7052:7054
     environment:
       - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
     volumes:
       - "./fabric-ca-server:/etc/hyperledger/fabric-ca-server"
       - "./wait-for-it.sh:/etc/hyperledger/wait-for-it.sh"
     command: sh -c '/etc/hyperledger/wait-for-it.sh mariadb-node-1:3306 -- fabric-ca-server start -b admin:adminpw'
     links:
       - mariadb-node-1
       - haproxy1

  admin-client:
    image: hyperledger/fabric-ca
    container_name: admin-client
    links:
      - haproxy0:haproxy0
    command: sh -c "sleep 25;fabric-ca-client enroll -u http://admin:adminpw@haproxy0:7054"

  admin-client1:
    image: hyperledger/fabric-ca
    container_name: admin-client1
    links:
      - haproxy0:haproxy0
    command: sh -c "sleep 25;fabric-ca-client enroll -u http://admin:adminpw@haproxy0:7054"
