/*
Copyright IBM Corp. 2018 All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

                 http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package mocks

import api "github.com/hyperledger/fabric-ca/api"

import lib "github.com/hyperledger/fabric-ca/lib"
import mock "github.com/stretchr/testify/mock"

// Config is an autogenerated mock type for the Config type
type Config struct {
	mock.Mock
}

// Enroll provides a mock function with given fields: rawurl, home
func (_m *Config) Enroll(rawurl string, home string) (*lib.EnrollmentResponse, error) {
	ret := _m.Called(rawurl, home)

	var r0 *lib.EnrollmentResponse
	if rf, ok := ret.Get(0).(func(string, string) *lib.EnrollmentResponse); ok {
		r0 = rf(rawurl, home)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.EnrollmentResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(rawurl, home)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenCSR provides a mock function with given fields: home
func (_m *Config) GenCSR(home string) error {
	ret := _m.Called(home)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(home)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCAName provides a mock function with given fields:
func (_m *Config) GetCAName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetEnrollmentRequest provides a mock function with given fields:
func (_m *Config) GetEnrollmentRequest() *api.EnrollmentRequest {
	ret := _m.Called()

	var r0 *api.EnrollmentRequest
	if rf, ok := ret.Get(0).(func() *api.EnrollmentRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.EnrollmentRequest)
		}
	}

	return r0
}

// GetID provides a mock function with given fields:
func (_m *Config) GetID() *api.RegistrationRequest {
	ret := _m.Called()

	var r0 *api.RegistrationRequest
	if rf, ok := ret.Get(0).(func() *api.RegistrationRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.RegistrationRequest)
		}
	}

	return r0
}

// GetMSPDir provides a mock function with given fields:
func (_m *Config) GetMSPDir() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetURL provides a mock function with given fields:
func (_m *Config) GetURL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
