fabric-ca:
   image: fabric-ca:latest
   ports:
     - "8888:8888"
   environment:
     - CA_CERTIFICATE=${CA_CERTIFICATE}
     - CA_KEY_CERTIFICATE=${CA_KEY_CERTIFICATE}
     - FABRIC_CA_CONFIG=${FABRIC_CA_CONFIG}
   volumes:
     - /config:/var/hyperledger/fabric_ca_config
     - /root/.fabric-ca:/var/hyperledger/fabric/.fabric-ca
   command: sh -c 'fabric-ca server start -ca ~/.fabric-ca/$CA_CERTIFICATE -ca-key ~/.fabric-ca/$CA_KEY_CERTIFICATE -config /config/$FABRIC_CA_CONFIG -address "0.0.0.0"'

admin-client:
   image: fabric-ca:latest
   environment:
     - CSR_CONFIG=${CSR_CONFIG}
   volumes:
     - /config:/var/hyperledger/fabric_ca_config
     - /root/.fabric-ca:/var/hyperledger/fabric/.fabric-ca
   command: sh -c "sleep 5;fabric-ca client enroll admin adminpw http://fabric-ca:8888 /config/$CSR_CONFIG"
   links:
     - fabric-ca

sdk-client:
   image: fabric-ca:latest
   environment:
     - CSR_CONFIG=${CSR_CONFIG}
   volumes:
     - /config:/var/hyperledger/fabric_ca_config
     - /root/.fabric-ca:/var/hyperledger/fabric/.fabric-ca
   command: sh -c "sleep 5;fabric-ca client enroll sdk sdkpw http://fabric-ca:8888 /config/$CSR_CONFIG"
   links:
     - fabric-ca

bob-client:
   image: fabric-ca:latest
   environment:
     - CSR_CONFIG=${CSR_CONFIG}
   volumes:
     - /config:/var/hyperledger/fabric_ca_config
     - /root/.fabric-ca:/var/hyperledger/fabric/.fabric-ca
   command: sh -c "sleep 5;fabric-ca client enroll bob bobpw http://fabric-ca:8888 /config/$CSR_CONFIG"
   links:
     - fabric-ca
