cop:
   image: hyperledger/fabric-cop
   ports:
     - "8888:8888"
   environment:
     - CA_CERTIFICATE=${CA_CERTIFICATE}
     - CA_KEY_CERTIFICATE=${CA_KEY_CERTIFICATE}
     - COP_CONFIG=${COP_CONFIG}
   volumes:
     - /config:/var/hyperledger/cop_config
     - /root/.cop:/var/hyperledger/fabric/.cop
   command: sh -c 'cop server start -ca ~/.cop/$CA_CERTIFICATE -ca-key ~/.cop/$CA_KEY_CERTIFICATE -config /config/$COP_CONFIG -address "0.0.0.0"'

admin-client:
   image: hyperledger/fabric-cop
   environment:
     - CSR_CONFIG=${CSR_CONFIG}
   volumes:
     - /config:/var/hyperledger/cop_config
     - /root/.cop:/var/hyperledger/fabric/.cop
   command: sh -c "sleep 5;cop client enroll admin adminpw http://cop:8888 /config/$CSR_CONFIG"
   links:
     - cop

sdk-client:
   image: hyperledger/fabric-cop
   environment:
     - CSR_CONFIG=${CSR_CONFIG}
   volumes:
     - /config:/var/hyperledger/cop_config
     - /root/.cop:/var/hyperledger/fabric/.cop
   command: sh -c "sleep 5;cop client enroll sdk sdkpw http://cop:8888 /config/$CSR_CONFIG"
   links:
     - cop

bob-client:
   image: hyperledger/fabric-cop
   environment:
     - CSR_CONFIG=${CSR_CONFIG}
   volumes:
     - /config:/var/hyperledger/cop_config
     - /root/.cop:/var/hyperledger/fabric/.cop
   command: sh -c "sleep 5;cop client enroll bob bobpw http://cop:8888 /config/$CSR_CONFIG"
   links:
     - cop
