/*
Copyright IBM Corp. 2018 All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

                 http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by mockery v1.0.0

package mocks

import api "github.com/hyperledger/fabric-ca/api"
import mock "github.com/stretchr/testify/mock"

// Identity is an autogenerated mock type for the Identity type
type Identity struct {
	mock.Mock
}

// Revoke provides a mock function with given fields: req
func (_m *Identity) Revoke(req *api.RevocationRequest) (*api.RevocationResponse, error) {
	ret := _m.Called(req)

	var r0 *api.RevocationResponse
	if rf, ok := ret.Get(0).(func(*api.RevocationRequest) *api.RevocationResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.RevocationResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*api.RevocationRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
