#!/bin/bash
FABRIC_CA=$GOPATH/src/github.com/hyperledger/fabric-ca
SCRIPTDIR="$FABRIC_CA/scripts/fvt"
export RESULTLOG="/tmp/fvt-test.results"
export STARTIME=$SECONDS
export RC=0
. $SCRIPTDIR/fabric-ca_utils
> $RESULTLOG

function runTests() {
   TimeStamp
   echo "Running fvt tests ..."

   for TLS in $SCRIPTDIR/tls.env $SCRIPTDIR/notls.env; do
      . $TLS
      export PATH=$PATH:$GOPATH/bin
      tests="$(find $SCRIPTDIR -maxdepth 1 -name "*test**sh")"
      for cmd in $tests; do
        echo ""
        echo "*******************"
        export TESTCASE="${cmd##*/}"
        echo "${cmd}"
        echo "*******************"
        ${cmd}
        RC=$((RC+$?))
        $SCRIPTDIR/fabric-ca_setup.sh -R
        echo ""
        echo ""
        echo ""
      done
   done
   echo "Finished running fvt tests"
   grep RC: $RESULTLOG
}
runTests > >( tee $RESULTLOG )
TESTCASE="fabric-ca-fvt"
CleanUp "$RC"
exit "$RC"
