# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
pr:
- master
- release-2.*
trigger: none

variables:
- template: variables.yml

jobs:
- job: VerifyBuild
  pool:
    vmImage: ubuntu-16.04
  dependsOn: []
  timeoutInMinutes: 60
  steps:
  - template: install_deps.yml
  - checkout: self
    path: 'go/src/github.com/hyperledger/fabric-ca'
    displayName: Checkout Fabric CA Code
  - script: make dist-all unit-test int-tests docs
    displayName: Run Unit and Integration Tests

- job: FVTTests
  pool:
    vmImage: ubuntu-16.04
  dependsOn: []
  timeoutInMinutes: 60
  steps:
  - template: install_deps.yml
  - checkout: self
    path: 'go/src/github.com/hyperledger/fabric-ca'
    displayName: Checkout Fabric CA Code
  - script: make docker-fvt
    displayName: Build FVT Test Image
  - script: docker run -v $(pwd):/opt/gopath/src/github.com/hyperledger/fabric-ca hyperledger/fabric-ca-fvt
    displayName: Run FVT Tests

- job: DocBuild
  pool:
    vmImage: ubuntu-16.04
  dependsOn: []
  timeoutInMinutes: 60
  steps:
  - template: install_deps.yml
  - script: apt-get install -y python-minimal tox
  - checkout: self
    path: 'go/src/github.com/hyperledger/fabric-ca'
    displayName: Checkout Fabric CA Code
  - script: tox -edocs
    displayName: Build Documentation
  - publish: '$(GIT_ORG_DIR)/fabric-ca/docs/_build/html'
    displayName: Publish Documentation
